project:
  type: website
  output-dir: docs

website:
  title: "Onur Furkan Gök | Analytics Lab"
  description: "Data Analytics Portfolio & EMU430 Coursework"
  
  navbar:
    pinned: true # Menüyü yukarı sabitler (Aşağı kaydırıldığında görünür kalır)
    search: true
    background: primary
    left:
      - text: "Home"
        icon: house-door
        href: index.qmd
      - text: "About Me"
        icon: person-badge
        href: about.qmd
      - text: "My Posts"
        icon: journal-code
        href: posts.qmd
      - text: "EMU430 Coursework"
        icon: mortarboard-fill
        menu:
          - text: "Assignments"
            icon: file-earmark-code
            href: assignments.qmd
          - text: "Project"
            icon: diagram-3
            href: project.qmd
            
    right:
      - icon: github
        href: https://github.com/onurfgg
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/onurfurkan
        aria-label: LinkedIn

  sidebar:
    - title: "EMU430 Assignments"
      style: "docked"
      background: light
      search: true
      collapse-level: 1 # Alt menüleri düzenli bir akordeon yapar
      contents:
        - assignments.qmd
        - section: "Homework Tasks"
          contents:
            - assignments/assignment-1.qmd
            - assignments/assignment-2.qmd  

  page-navigation: true
  back-to-top-navigation: true
  
  page-footer:
    left: "© 2026 Onur Furkan Gök"
    center: "Hacettepe IE - EMU430 Spring" 
    right:
      - icon: github
        href: https://github.com/onurfgg
      - icon: linkedin
        href: https://linkedin.com/in/onurfurkan
    border: true

format:
  html:
    theme:
      dark: [darkly, custom.scss] # Karanlık ve neon tema için darkly tabanını kullanıyoruz
      light: [cosmo, custom.scss]
    css: styles.css
    highlight-style: atom-one
    code-fold: true
    code-copy: hover
    code-tools: true
    toc: true
    toc-location: right
    smooth-scroll: true